project_id = "ngcmmvyebvekyutbixee"

[functions.ai-notes]
verify_jwt = true

[functions.process-material]
verify_jwt = true

[functions.material-chat]
verify_jwt = true

[functions.regenerate-content]
verify_jwt = true

[functions.paystack]
verify_jwt = false
